/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.javasync.idioms;

import org.junit.Test;

import java.io.IOException;
import java.util.concurrent.CompletableFuture;

import static org.javasync.idioms.Resources.DISCOURSE_ON_THE_METHOD;
import static org.javasync.idioms.Resources.DIVINE_COMEDY;
import static org.javasync.idioms.Resources.METAMORPHOSIS;
import static org.junit.Assert.assertEquals;

public class AsyncIoRxsTest {
    @Test public void testRxForThreeFiles() throws IOException {
        CompletableFuture finished = new CompletableFuture();
        AsyncIoRx
            .countLines(METAMORPHOSIS, DISCOURSE_ON_THE_METHOD, DIVINE_COMEDY)
            .thenAccept(count -> assertEquals(10423, count.intValue()))
            .thenAccept(finished::complete)
            .exceptionally(err -> { finished.completeExceptionally(err); return null; });
        finished.join();
    }
}
