/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.javasync.idioms;

import org.junit.Test;

import java.util.concurrent.ExecutionException;

import static org.javasync.idioms.Resources.DISCOURSE_ON_THE_METHOD;
import static org.javasync.idioms.Resources.DIVINE_COMEDY;
import static org.javasync.idioms.Resources.METAMORPHOSIS;
import static org.junit.Assert.assertEquals;

public class TasksTest {
    @Test public void testTasks1ForTwoFiles() throws InterruptedException, ExecutionException {
        long count = Tasks1.countLines(
                        METAMORPHOSIS,
                        DISCOURSE_ON_THE_METHOD);
        assertEquals(4745, count);
    }

    @Test public void testTasks2ForThreeFiles() throws Exception {
        try(Tasks2 ts = new Tasks2(3)){
            long count = ts.countLines(
                            METAMORPHOSIS,
                            DISCOURSE_ON_THE_METHOD,
                            DIVINE_COMEDY);
            assertEquals(10423, count);
        }
    }
}
