/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.javasync.idioms;

import org.junit.Test;

import java.io.IOException;

import static org.javasync.idioms.Resources.DISCOURSE_ON_THE_METHOD;
import static org.javasync.idioms.Resources.DIVINE_COMEDY;
import static org.javasync.idioms.Resources.METAMORPHOSIS;
import static org.junit.Assert.assertEquals;

public class ThreadsTest {
    @Test public void testThreads1ForTwoFiles() throws InterruptedException {
        long count = Threads1.countLines(
                        METAMORPHOSIS,
                        DISCOURSE_ON_THE_METHOD);
        assertEquals(4745, count);
    }

    @Test public void testThreads2ForThreeFiles() throws InterruptedException {
        long count = Threads2.countLines(
                        METAMORPHOSIS,
                        DISCOURSE_ON_THE_METHOD,
                        DIVINE_COMEDY);
        assertEquals(10423, count);
    }
}
